"""scripts/sync_codex_mirror.py — .claude/skills의 Codex 미러(.codex/skills) 생성

Codex(codex CLI)는 Claude Code와 달리 skill runtime이 없어 `.claude/skills/`를
자동 로드하지 못한다. 그래서 AGENTS.md가 가리킬 수 있도록 `.claude/skills`의
생성 미러를 `.codex/skills`에 만든다.

`.claude/skills`가 단일 진실의 원천(SSOT). `.codex/skills`는 생성물이다 —
텍스트 파일 안의 ".claude/skills" 토큰만 ".codex/skills"로 치환하고 나머지는
byte-identical 복사. 스킬 수정 후 반드시 재실행한다.

사용법:
    python scripts/sync_codex_mirror.py          # 미러 재생성
    python scripts/sync_codex_mirror.py --check  # stale이면 exit 1 (쓰지 않음)
"""
from __future__ import annotations

import argparse
import os
import shutil
import stat
import sys
import tempfile
import time
from pathlib import Path

# Windows 콘솔(cp949 등)에서 인코딩 불가 문자로 죽지 않도록.
# 이 파일의 안내 문구에는 cp949 에 없는 글자(— · ⚠)가 들어 있다.
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(errors="replace")
    except (AttributeError, ValueError):
        pass

# scripts/sync_codex_mirror.py: parents[0]=scripts [1]=repo root
REPO_ROOT = Path(__file__).resolve().parents[1]
SRC = REPO_ROOT / ".claude" / "skills"
DST = REPO_ROOT / ".codex" / "skills"

TEXT_SUFFIXES = {".md", ".py", ".sh", ".json", ".txt", ".svg", ".cfg",
                 ".toml", ".yml", ".yaml", ".ini"}
EXCLUDE_NAMES = {"__pycache__", ".DS_Store"}
# host-only 스킬 제외용 (예: slide의 codex-image). 이 repo엔 없음.
EXCLUDE_REL_PREFIXES: set[tuple[str, ...]] = set()
OLD_TOKEN = ".claude" + "/skills"
NEW_TOKEN = ".codex" + "/skills"
GENERATED_MARKER = f"""# Generated Codex Skills Mirror

This directory is generated by `sync_codex_mirror.py`.
Do not hand-edit files under `{NEW_TOKEN}`.
Edit `{OLD_TOKEN}`, then regenerate this mirror.
"""


def _iter_files(root: Path):
    if not root.exists():
        return
    for p in sorted(root.rglob("*")):
        rel = p.relative_to(root)
        if any(part in EXCLUDE_NAMES for part in rel.parts):
            continue
        if any(rel.parts[:len(prefix)] == prefix for prefix in EXCLUDE_REL_PREFIXES):
            continue
        if p.suffix == ".pyc":
            continue
        if p.is_file():
            yield p


def _transform_bytes(path: Path, data: bytes) -> bytes:
    if path.suffix.lower() in TEXT_SUFFIXES:
        try:
            text = data.decode("utf-8")
        except UnicodeDecodeError:
            return data
        return text.replace(OLD_TOKEN, NEW_TOKEN).encode("utf-8")
    return data


def _force_writable(func, path, _exc):
    """읽기 전용 속성 때문에 지워지지 않는 경우를 한 번 풀어 준다."""
    os.chmod(path, stat.S_IWRITE)
    func(path)


# rmtree 의 오류 콜백 인자 이름이 3.12 에서 바뀌었다(onerror → onexc).
# 이 저장소는 Python 3.10 이상을 지원한다고 문서에 적혀 있으므로 양쪽을 다 지원한다.
# 두 콜백의 시그니처는 (func, path, 세번째) 로 같아서 함수는 하나로 충분하다.
_RMTREE_HANDLER = ({"onexc": _force_writable} if sys.version_info >= (3, 12)
                   else {"onerror": _force_writable})


def _rmtree_resilient(path: Path, attempts: int = 5) -> None:
    """Windows 에서 rmtree 는 자주 '잠깐' 실패한다.

    OneDrive·백신·검색 인덱서가 방금 쓴 파일의 핸들을 잠시 붙들고 있으면
    WinError 5(액세스 거부) / 32(사용 중) 가 난다. 대개 수백 ms 뒤에 풀린다.
    한 번 실패했다고 포기하면 미러가 반쯤 지워진 채 남는다.
    """
    for attempt in range(attempts):
        try:
            shutil.rmtree(path, **_RMTREE_HANDLER)
            return
        except OSError:
            if attempt == attempts - 1:
                raise
            time.sleep(0.2 * (attempt + 1))


def _populate(dst: Path) -> None:
    for src_file in _iter_files(SRC):
        rel = src_file.relative_to(SRC)
        out = dst / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(_transform_bytes(src_file, src_file.read_bytes()))
    dst.mkdir(parents=True, exist_ok=True)
    (dst / "_GENERATED.md").write_text(GENERATED_MARKER, encoding="utf-8")


def build_mirror(dst: Path) -> None:
    """미러를 통째로 새로 만든 뒤 마지막에 한 번만 갈아끼운다.

    예전에는 `rmtree(dst)` 로 먼저 지우고 그 자리에서 다시 채웠다. 그러면 삭제나
    복사가 중간에 실패했을 때 **미러가 반쯤 지워진 상태로 남는다** — 그리고 그 다음
    `--check` 는 stale 을 보고하므로, 원인이 파일 잠금이었다는 사실이 드러나지 않는다.
    지금은 옆에 완성본을 만들어 두고 마지막에 교체하므로, 도중에 실패하면 **기존
    미러가 그대로 살아 있다.**
    """
    staging = dst.parent / (dst.name + ".new")
    if staging.exists():
        _rmtree_resilient(staging)
    staging.parent.mkdir(parents=True, exist_ok=True)
    try:
        _populate(staging)
        if dst.exists():
            _rmtree_resilient(dst)
        os.replace(staging, dst)        # 같은 디렉터리 안이라 단순 rename 이다
    finally:
        if staging.exists():
            _rmtree_resilient(staging)


def _stale_files(mirror: Path, fresh: Path) -> list[str]:
    a = {p.relative_to(mirror) for p in _iter_files(mirror)}
    b = {p.relative_to(fresh) for p in _iter_files(fresh)}
    out = []
    for rel in sorted(a | b):
        fa, fb = mirror / rel, fresh / rel
        if not fa.exists() or not fb.exists() or fa.read_bytes() != fb.read_bytes():
            out.append(str(rel))
    return out


def check() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        fresh = Path(tmp) / "skills"
        build_mirror(fresh)
        stale = _stale_files(DST, fresh)
    if stale:
        sys.stderr.write("[sync_codex_mirror] .codex/skills is STALE:\n")
        for rel in stale[:40]:
            sys.stderr.write(f"  - {rel}\n")
        if len(stale) > 40:
            sys.stderr.write(f"  ... and {len(stale) - 40} more\n")
        sys.stderr.write("  Fix: python scripts/sync_codex_mirror.py\n")
        return 1
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate/verify the .codex/skills mirror.")
    ap.add_argument("--check", action="store_true",
                    help="Exit 1 if the mirror is stale; do not write.")
    args = ap.parse_args()
    if args.check:
        return check()
    build_mirror(DST)
    print(f"[sync_codex_mirror] regenerated {DST} from {SRC}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
